CREATE OR REPLACE FUNCTION CALCULAR_BONIFICACION (
    p_id EMPLEADOS.ID_EMPLEADO%TYPE
) 
RETURN NUMBER
IS
    v_salario EMPLEADOS.SALARIO%TYPE;
BEGIN
    SELECT SALARIO
    INTO v_salario
    FROM EMPLEADOS
    WHERE ID_EMPLEADO = p_id;

    RETURN v_salario * 0.10;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

SET SERVEROUTPUT ON;
DECLARE
    v_bono NUMBER;
BEGIN
    v_bono := CALCULAR_BONIFICACION(1);

    DBMS_OUTPUT.PUT_LINE('La bonificación es: ' || v_bono);
END;
/